### PR TITLE
appSwitcher : Add no running apps indicator

### PR DESCRIPTION
**Pull request by mathew-dennis**
This will show up when there are no runnig apps and the app list is empty

### CODE REVIEW

**Comment by mathew-dennis** [comment]
A video of this in action 

https://github.com/cutie-shell/cutie-home/assets/78794223/706ee276-39ed-45a2-9a3e-08f5cfc42a69

A picture of no running app text which appears when there are no apps
IMG_20240414_083900

**Review by erikinkinen — CHANGES_REQUESTED** [review]
If you use `anchors.fill`, you should not use any other anchors. Looking at your use case however, I think you might want to use `anchors.centerIn`.

**Comment by mathew-dennis** [comment]
Got it .will fix that and update pr  next week .

**Comment by mathew-dennis** [comment]
@erikinkinen I updated the pr. Can you plz take a look

**Review by erikinkinen — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
